In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
#Import data
df = pd.read_csv("financial_data_1000_records.csv")

In [9]:
#Explore data 
# head, info, describe, 
df.head()

,customer_id,full_name,age,country,account_open_date,transaction_date,transaction_type,transaction_amount,account_balance,is_international
0,221958,Jordan Smith,34,India,2018-04-14,2024-03-11,ATM,1584.01,17857.01,False
1,771155,Casey Williams,22,France,2019-06-14,2024-04-27,Online,-463.09,13702.98,False
2,231932,Morgan Brown,46,Germany,2017-07-02,2023-01-25,POS,1622.31,20970.86,False
3,465838,Jordan Anderson,21,India,2016-03-29,2024-10-14,ATM,3854.46,20404.84,False
4,359178,Jordan Thomas,27,Italy,2015-02-06,2023-04-27,Online,2777.94,20849.51,False

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         1000 non-null   int64
 1   full_name           1000 non-null   object
 2   age                 1000 non-null   int64
 3   country             1000 non-null   object
 4   account_open_date   1000 non-null   object
 5   transaction_date    1000 non-null   object
 6   transaction_type    1000 non-null   object
 7   transaction_amount  1000 non-null   float64
 8   account_balance     1000 non-null   float64
 9   is_international    1000 non-null   bool
dtypes: bool(1), float64(2), int64(2), object(5)
memory usage: 71.4+ KB

In [11]:
df.describe()

         customer_id          age  transaction_amount  account_balance
count    1000.000000  1000.000000          1000.00000      1000.000000
mean   538112.094000    46.338000          2333.87194     12268.217630
std    262574.257707    16.586406          1560.76329      6004.114838
min    100404.000000    18.000000          -497.56000       112.690000
25%    301536.000000    32.000000          1010.01000      7144.540000
50%    538556.500000    46.000000          2407.58000     12098.360000
75%    762517.000000    61.000000          3679.57000     17119.870000
max    999684.000000    74.000000          4998.43000     24950.180000

In [12]:
# data components : columns, index, values
df.values

array([[221958, 'Jordan Smith', 34, ..., 1584.01, 17857.01, False],
       [771155, 'Casey Williams', 22, ..., -463.09, 13702.98, False],
       [231932, 'Morgan Brown', 46, ..., 1622.31, 20970.86, False],
       ...,
       [170390, 'Riley Thomas', 55, ..., 3167.25, 12307.39, False],
       [807689, 'Alex Smith', 25, ..., 18.8, 9104.96, False],
       [353490, 'Jordan Smith', 22, ..., 3614.03, 22358.89, False]],
      dtype=object)

In [13]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [14]:
df.columns

Index(['customer_id', 'full_name', 'age', 'country', 'account_open_date',
       'transaction_date', 'transaction_type', 'transaction_amount',
       'account_balance', 'is_international'],
      dtype='object')

### PANDAS SORTING & SUBSETTING

In [16]:
df.sort_values("account_balance", ascending = False)

,customer_id,full_name,age,country,account_open_date,transaction_date,transaction_type,transaction_amount,account_balance,is_international
527,834994,Jamie Anderson,47,France,2016-05-04,2024-08-10,Deposit,4997.49,24950.18,True
692,737144,Drew Thomas,38,Netherlands,2016-12-15,2023-08-15,ATM,4668.08,24606.57,True
268,170467,Morgan Johnson,52,UK,2024-09-04,2024-12-01,Deposit,4619.44,24547.77,False
863,464167,Casey Williams,30,Italy,2018-02-27,2023-12-29,Deposit,4732.93,24450.46,False
616,149115,Riley Smith,55,UK,2015-01-19,2023-06-11,ATM,4642.47,24165.52,True
...,...,...,...,...,...,...,...,...,...,...
562,566882,Sam Jones,54,Spain,2024-05-16,2024-11-09,ATM,281.94,574.71,True
886,538661,Sam Wilson,56,USA,2021-10-29,2023-11-28,Online,-426.48,508.61,False
676,214352,Cameron Smith,44,Australia,2021-12-20,2023-09-05,Deposit,-488.90,331.34,True
157,572525,Sam Brown,23,France,2023-10-07,2023-01-17,Transfer,55.18,217.68,False
930,909956,Riley Anderson,37,Netherlands,2019-05-21,2024-01-12,ATM,-419.54,112.69,False

In [17]:
df.sort_values(["age","account_balance"],ascending = [False,True])

,customer_id,full_name,age,country,account_open_date,transaction_date,transaction_type,transaction_amount,account_balance,is_international
677,969474,Drew Anderson,74,Netherlands,2021-08-08,2023-06-05,ATM,457.45,584.24,True
882,651820,Riley Johnson,74,UK,2017-10-13,2023-01-01,POS,2308.09,3166.01,False
337,690978,Morgan Johnson,74,Germany,2017-05-23,2023-07-07,ATM,2419.06,3714.98,False
560,352764,Drew Jones,74,Germany,2019-12-05,2024-07-07,Deposit,-330.28,4022.31,True
767,128295,Jamie Johnson,74,Canada,2017-12-08,2023-05-07,Online,-344.29,4247.69,True
...,...,...,...,...,...,...,...,...,...,...
743,727438,Taylor Thomas,18,Italy,2018-04-10,2024-05-22,ATM,634.20,16921.55,True
552,473632,Jamie Miller,18,Germany,2022-08-25,2024-11-10,ATM,374.64,16994.64,False
270,722794,Jamie Anderson,18,India,2018-08-26,2024-11-26,Online,3554.03,18653.34,True
80,905889,Casey Williams,18,UK,2016-03-23,2023-09-03,Online,-182.42,18892.93,False
54,589492,Riley Williams,18,Spain,2022-01-26,2023-12-25,Deposit,2496.55,19783.01,False

In [18]:
#SUBSETTING
df.columns

Index(['customer_id', 'full_name', 'age', 'country', 'account_open_date',
       'transaction_date', 'transaction_type', 'transaction_amount',
       'account_balance', 'is_international'],
      dtype='object')

In [23]:
df1 = df[['customer_id', 'full_name', 'transaction_date', 'transaction_type', 'transaction_amount',
       'account_balance']]

In [25]:
df1[df1['transaction_date']>"2024-01-01"]

,customer_id,full_name,transaction_date,transaction_type,transaction_amount,account_balance
0,221958,Jordan Smith,2024-03-11,ATM,1584.01,17857.01
1,771155,Casey Williams,2024-04-27,Online,-463.09,13702.98
3,465838,Jordan Anderson,2024-10-14,ATM,3854.46,20404.84
5,744167,Sam Smith,2024-04-26,POS,56.93,18734.99
6,210268,Alex Johnson,2024-01-27,ATM,4159.27,20206.10
...,...,...,...,...,...,...
992,415557,Cameron Johnson,2024-02-25,Transfer,1859.42,19924.42
993,983671,Cameron Brown,2024-07-21,ATM,605.86,11151.37
995,350875,Taylor Brown,2024-07-12,Deposit,3549.26,10224.05
997,170390,Riley Thomas,2024-10-30,ATM,3167.25,12307.39
999,353490,Jordan Smith,2024-03-19,Deposit,3614.03,22358.89

In [27]:
# filter out dataset for only transactions 
df1[df1["transaction_type"].isin(["ATM","PS"])]

,customer_id,full_name,transaction_date,transaction_type,transaction_amount,account_balance
0,221958,Jordan Smith,2024-03-11,ATM,1584.01,17857.01
3,465838,Jordan Anderson,2024-10-14,ATM,3854.46,20404.84
6,210268,Alex Johnson,2024-01-27,ATM,4159.27,20206.10
8,154886,Cameron Thomas,2023-03-20,ATM,4129.48,4343.28
13,275203,Casey Smith,2024-08-30,ATM,4846.14,24073.21
...,...,...,...,...,...,...
985,762301,Taylor Miller,2024-01-15,ATM,952.02,20844.20
986,650222,Morgan Miller,2024-11-09,ATM,1783.83,5900.48
993,983671,Cameron Brown,2024-07-21,ATM,605.86,11151.37
994,404462,Drew Thomas,2023-07-12,ATM,2328.11,11406.85
997,170390,Riley Thomas,2024-10-30,ATM,3167.25,12307.39

In [29]:
df1[df1['transaction_type'].isin(['ATM', 'PS'])]

,customer_id,full_name,transaction_date,transaction_type,transaction_amount,account_balance
0,221958,Jordan Smith,2024-03-11,ATM,1584.01,17857.01
3,465838,Jordan Anderson,2024-10-14,ATM,3854.46,20404.84
6,210268,Alex Johnson,2024-01-27,ATM,4159.27,20206.10
8,154886,Cameron Thomas,2023-03-20,ATM,4129.48,4343.28
13,275203,Casey Smith,2024-08-30,ATM,4846.14,24073.21
...,...,...,...,...,...,...
985,762301,Taylor Miller,2024-01-15,ATM,952.02,20844.20
986,650222,Morgan Miller,2024-11-09,ATM,1783.83,5900.48
993,983671,Cameron Brown,2024-07-21,ATM,605.86,11151.37
994,404462,Drew Thomas,2023-07-12,ATM,2328.11,11406.85
997,170390,Riley Thomas,2024-10-30,ATM,3167.25,12307.39

In [30]:
#ASSUME TRASACT_AMOUNT IS THE LAST TRANSACTION
# PREVIOUS TRANSACTION BALANCE IS transaction amount + account_balance
df1['previous_tran_balance'] = df1['transaction_amount'] + df1['account_balance']
df1

C:\Users\Admin\AppData\Local\Temp\ipykernel_13008\3427023693.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['previous_tran_balance'] = df1['transaction_amount'] + df1['account_balance']

,customer_id,full_name,transaction_date,transaction_type,transaction_amount,account_balance,previous_tran_balance
0,221958,Jordan Smith,2024-03-11,ATM,1584.01,17857.01,19441.02
1,771155,Casey Williams,2024-04-27,Online,-463.09,13702.98,13239.89
2,231932,Morgan Brown,2023-01-25,POS,1622.31,20970.86,22593.17
3,465838,Jordan Anderson,2024-10-14,ATM,3854.46,20404.84,24259.30
4,359178,Jordan Thomas,2023-04-27,Online,2777.94,20849.51,23627.45
...,...,...,...,...,...,...,...
995,350875,Taylor Brown,2024-07-12,Deposit,3549.26,10224.05,13773.31
996,563389,Drew Thomas,2023-05-28,POS,1900.31,13725.68,15625.99
997,170390,Riley Thomas,2024-10-30,ATM,3167.25,12307.39,15474.64
998,807689,Alex Smith,2023-07-21,Online,18.80,9104.96,9123.76
999,353490,Jordan Smith,2024-03-19,Deposit,3614.03,22358.89,25972.92

In [31]:
#.agg method 

def sum_sta(column):
    return column.describe()

In [32]:
df1['previous_tran_balance'].agg(sum_sta)

count     1000.000000
mean     14602.089570
std       6579.423907
min       -306.850000
25%       9653.920000
50%      14428.925000
75%      19635.225000
max      29947.670000
Name: previous_tran_balance, dtype: float64

In [33]:
# droping duplicates 
dup_df = df1.copy()

In [35]:
dup_df.drop_duplicates(subset ='transaction_type')
dup_df.drop_duplicates(subset = 'transaction_type')

,customer_id,full_name,transaction_date,transaction_type,transaction_amount,account_balance,previous_tran_balance
0,221958,Jordan Smith,2024-03-11,ATM,1584.01,17857.01,19441.02
1,771155,Casey Williams,2024-04-27,Online,-463.09,13702.98,13239.89
2,231932,Morgan Brown,2023-01-25,POS,1622.31,20970.86,22593.17
9,237337,Alex Anderson,2024-08-02,Deposit,2691.22,12061.15,14752.37
10,621430,Morgan Anderson,2023-06-22,Transfer,2578.29,14044.42,16622.71

In [36]:
#drop duplicates pairs 
dup_df.drop_duplicates(subset = ['full_name','previous_tran_balance'])

,customer_id,full_name,transaction_date,transaction_type,transaction_amount,account_balance,previous_tran_balance
0,221958,Jordan Smith,2024-03-11,ATM,1584.01,17857.01,19441.02
1,771155,Casey Williams,2024-04-27,Online,-463.09,13702.98,13239.89
2,231932,Morgan Brown,2023-01-25,POS,1622.31,20970.86,22593.17
3,465838,Jordan Anderson,2024-10-14,ATM,3854.46,20404.84,24259.30
4,359178,Jordan Thomas,2023-04-27,Online,2777.94,20849.51,23627.45
...,...,...,...,...,...,...,...
995,350875,Taylor Brown,2024-07-12,Deposit,3549.26,10224.05,13773.31
996,563389,Drew Thomas,2023-05-28,POS,1900.31,13725.68,15625.99
997,170390,Riley Thomas,2024-10-30,ATM,3167.25,12307.39,15474.64
998,807689,Alex Smith,2023-07-21,Online,18.80,9104.96,9123.76
999,353490,Jordan Smith,2024-03-19,Deposit,3614.03,22358.89,25972.92